Task 119339: Change log level [TAGS NOT PUSHED] AB#119339
FerryIslands/express-nemo-bootstrap pull request #55
Opened 2023-08-14 09:40 UTC by esepato

2023-08-14 22:38 UTC, ohritz requested changes

2023-08-14 22:38 UTC, ohritz commented on package.json
> +  "version": "1.6.0",
Maybe not "waste" a minor version, and 1.5.1 is sufficient?

2023-08-14 22:38 UTC, ohritz commented on logger.js
> +    logContext = extend(dataProps, logContext)
Nice!

2023-08-14 22:38 UTC, ohritz commented on logger.js
> +    context: extend(defaultStructure.context, context)
when not giving an empty object as the target, it seems the `defaultStructure.context` will be a reference and any unfortunate mutations to the `logContext.context` will mutate the `defaultStructure.context`.
I had to verify in a jsfiddle: https://jsfiddle.net/ohreo/ydfo21pa/3/#&togetherjs=14k2wvqnot

2023-08-15 05:45 UTC, esepato commented on logger.js
> +    context: extend(defaultStructure.context, context)
Oh, wow. Good catch, putting the empty object back.

2023-08-15 05:49 UTC, esepato commented on package.json
> +  "version": "1.6.0",
No big deal for me. I thought that as a consumer of the package, you will know that something is breaking with the minor, and in this case it is the logging behaviour.

2023-08-15 06:25 UTC, esepato commented
> In `middlewares.js` `requestResponseLogger` is created from another npm package (expressHttpContextRequestResponseLogger) which is "ours" the default options object there looks like this:
> 
> ```js
> const defaults = {
>   loggerFunctionName: 'debug',
>   logEventFactory: (req, res) =>
>     `${req.method} ${req.url} - HTTP ${res.statusCode}`
> }
> ```
> 
> With the change from default loglevel being set to 'info' all request loging will be ignored/filtered out. Is that what we want?

I assume not! I saw that some request logs actually were removed. Nice catch.

So ideally we would like to use the same as default? The request logging doesn't seem to be optional, it will always be used and currently always use the default level since this solution doesn't provide any way to override it.

2023-08-15 06:57 UTC, ohritz commented
> > In `middlewares.js` `requestResponseLogger` is created from another npm package (expressHttpContextRequestResponseLogger) which is "ours" the default options object there looks like this:
> > ```js
> > const defaults = {
> >   loggerFunctionName: 'debug',
> >   logEventFactory: (req, res) =>
> >     `${req.method} ${req.url} - HTTP ${res.statusCode}`
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With the change from default loglevel being set to 'info' all request loging will be ignored/filtered out. Is that what we want?
> 
> I assume not! I saw that some request logs actually were removed. Nice catch.
> 
> So ideally we would like to use the same as default? The request logging doesn't seem to be optional, it will always be used and currently always use the default level since this solution doesn't provide any way to override it.

I think you can just set in express-nemo-bootstrap:middleware.js 
```js
const requestResponseLogger = expressHttpContextRequestResponseLogger({
    logEventFactory: logEventFactory.createRequestResponseLogEvent,
    loggerFunctionName: "info"
  })
```

we are already overiding the default logEventFactory.

2023-08-15 09:06 UTC, ohritz commented on logger.js
> +    const { message, level, timestamp, ...dataProps } = data
```suggestion
    // eslint-disable-next-line no-unused-vars
    const { message, level, timestamp, ...dataProps } = data
```

Just add this, I get an error in vs-code

2023-08-15 12:47 UTC, merged